
# ~/.config/yazi/yazi.toml

[mgr]
# Show hidden files by default
show_hidden = true
# Sort files naturally (e.g., 1.md < 2.md < 10.md)
sort_dir_first = true
sort_by = "natural"

[opener]
# Define your text editor using the $EDITOR environment variable
edit = [
  { run = '${EDITOR:=vi} "$@"', block = true, desc = "$EDITOR", for = "unix" },
]


[open]
# Force text files and empty files to use your 'edit' opener defined above
prepend_rules = [
  { mime = "text/*",  use = "edit" },
  { mime = "inode/empty", use = "edit" },
]
